apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-22ba"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-22ba"
  template:
    metadata:
      labels:
        app: "myakscluster-22ba"
    spec:
      containers:
        - name: "myakscluster-22ba"
          image: "azure1aks.azurecr.io/myakscluster"
          ports:
          - containerPort: 80